import { getPublicGamesPage } from "@/lib/db";
import PublicGamesList from "@/components/public-games-list";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const PAGE_SIZE = 20;

export default async function PublicGamesPage() {
  const { games, total } = await getPublicGamesPage(PAGE_SIZE, 0);

  return (
    <div className="max-w-6xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Public Games</h1>
        <p className="text-muted-foreground">
          Discover games created by the community. All games are generated by AI.
        </p>
      </div>

      <PublicGamesList initialGames={games} total={total} pageSize={PAGE_SIZE} />
    </div>
  );
}
