import { getPublicGames } from "@/lib/db";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Gamepad2, User, Calendar } from "lucide-react";
import GameIframe from "@/components/game-iframe";
import Link from "next/link";


export const runtime = "nodejs";
export const dynamic = "force-dynamic";


export default async function PublicGamesPage() {
  const games = await getPublicGames(20);

  return (
    <div className="max-w-6xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Public Games</h1>
        <p className="text-muted-foreground">
          Discover games created by the community. All games are generated by AI.
        </p>
      </div>

      {games.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Gamepad2 className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No public games yet</h3>
            <p className="text-muted-foreground mb-4">Be the first to create a game!</p>
            <Button asChild>
              <Link href="/">Create a Game</Link>
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {games.map((game: any) => (
            <Card key={game.id} className="flex flex-col">
              <CardHeader>
                <CardTitle className="line-clamp-1">{game.title}</CardTitle>
                <CardDescription className="line-clamp-2">{game.description || "AI-generated game"}</CardDescription>
              </CardHeader>
              <CardContent className="relative flex-grow pb-28">
                <div className="absolute bottom-4 left-4">
                  <div className="w-48 h-28 overflow-hidden rounded-md border bg-background shadow-sm">
                    <GameIframe
                      html={game.htmlContent}
                      title={`${game.title} preview`}
                      fixedWidth={520}
                      fixedHeight={320}
                      scale={0.3}
                      className="pointer-events-none"
                    />
                  </div>
                </div>
                <div className="absolute bottom-4 right-4 text-xs text-muted-foreground space-y-1 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <User className="h-3.5 w-3.5" />
                    <span>{game.user?.name || game.user?.email || "Anonymous"}</span>
                  </div>
                  <div className="flex items-center justify-end gap-2">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>{new Date(game.createdAt).toLocaleDateString()}</span>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button className="w-full" asChild>
                  <Link href={`/game/${game.id}`}>Play Game</Link>
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}